6 feature 8 user reporter
CSC207-2022F-UofT/course-project-unite-group-115 pull request #22
Opened 2022-11-21 22:52 UTC by aurorali17

user reporter, database test and entities test

2022-11-28 22:49 UTC, jastti requested changes
Since this function is not implemented, you can change it to a "back" Jbutton and go back to the last page

2022-11-28 22:49 UTC, jastti commented on src/main/java/frameworks_and_drivers/Report_First_Screen.java
> +        JButton block = new JButton("Block User");
Since this function is not implemented, you can change it to a "back" Jbutton and go back to the last page

2022-12-02 03:07 UTC, jastti submitted a review, later dismissed

2022-12-08 04:20 UTC, closed without merging

2022-12-08 04:20 UTC, aurorali17 commented
Replaced with new pull request